### ISSUE TITLE
Add Dates To Posts

### ISSUE THREAD

**Issue by willisplummer** [davish/website-astro#32]
Hey man, I found your post "Setting up Nix on macOS" while trying to find out the best way to run home-manager on mac, and the info was super helpful but then I was like "I wonder how current this information is" and I started poking around in the source to try to find a created-at or something.

Finally, I navigated back to the TIL index and saw the post date there, but it would be great to include created at or last updated at on the individual posts for people coming in from Google.

Hope this is helpful feedback!

**Comment by davish** [comment]
thanks for the feedback! I've added the "last modified" time to the bottom of all TILs.
